fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Trascastro\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: false
    from_email:
        address:        marc.rodriguez451@gmail.com
        sender_name:    Marc Rodríguez
