<?php

namespace AppBundle\Repository;

/**
 * DescripcionImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescripcionImagenRepository extends \Doctrine\ORM\EntityRepository
{
}
