<?php

namespace AppBundle\Repository;

/**
 * PedirHoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedirHoraRepository extends \Doctrine\ORM\EntityRepository
{
}
