<?php

namespace AppBundle\Repository;

/**
 * TaggingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaggingRepository extends \Doctrine\ORM\EntityRepository
{
}
