user:
    resource: "@UserBundle/Resources/config/routing.yml"

app.inicio:
    resource: "@AppBundle/Controller/InicioController.php"
    type: annotation

app.post:
    resource: "@AppBundle/Controller/PostController.php"
    type: annotation
    prefix: /posts

app.comment:
    resource: "@AppBundle/Controller/CommentController.php"
    type: annotation
    prefix: /comments

