user:
    resource: "@UserBundle/Resources/config/routing.yml"

app.inicio:
    resource: "@AppBundle/Controller/InicioController.php"
    type: annotation

app.post:
    resource: "@AppBundle/Controller/PostController.php"
    type: annotation
    prefix: /posts

app.comment:
    resource: "@AppBundle/Controller/CommentController.php"
    type: annotation
    prefix: /comments

app.contact:
    resource: "@AppBundle/Controller/ContactoController.php"
    type: annotation
    prefix: /contact

app.galeria:
    resource: "@AppBundle/Controller/GaleriaController.php"
    type: annotation
    prefix: /galeria

app.hora:
    resource: "@AppBundle/Controller/PedirHoraController.php"
    type: annotation
    prefix: /pedir-hora

app.quienes:
    resource: "@AppBundle/Controller/QuienesSomosController.php"
    type: annotation
    prefix: /quienes-somos

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"